-- DCCT-NIDS Block 6 provenance reconstruction
-- Generated: 2026-07-10T06:36:38.116343+00:00
--
-- Reproduces the exact Block 4 duplicate definition while
-- preserving chronological source-file metadata.

CREATE TABLE retained_with_provenance AS
SELECT
    "Protocol",
                "Flow Duration",
                "Total Fwd Packets",
                "Total Backward Packets",
                "Fwd Packets Length Total",
                "Bwd Packets Length Total",
                "Fwd Packet Length Max",
                "Fwd Packet Length Min",
                "Fwd Packet Length Mean",
                "Fwd Packet Length Std",
                "Bwd Packet Length Max",
                "Bwd Packet Length Min",
                "Bwd Packet Length Mean",
                "Bwd Packet Length Std",
                "Flow Bytes/s",
                "Flow Packets/s",
                "Flow IAT Mean",
                "Flow IAT Std",
                "Flow IAT Max",
                "Flow IAT Min",
                "Fwd IAT Total",
                "Fwd IAT Mean",
                "Fwd IAT Std",
                "Fwd IAT Max",
                "Fwd IAT Min",
                "Bwd IAT Total",
                "Bwd IAT Mean",
                "Bwd IAT Std",
                "Bwd IAT Max",
                "Bwd IAT Min",
                "Fwd PSH Flags",
                "Bwd PSH Flags",
                "Fwd URG Flags",
                "Bwd URG Flags",
                "Fwd Header Length",
                "Bwd Header Length",
                "Fwd Packets/s",
                "Bwd Packets/s",
                "Packet Length Min",
                "Packet Length Max",
                "Packet Length Mean",
                "Packet Length Std",
                "Packet Length Variance",
                "FIN Flag Count",
                "SYN Flag Count",
                "RST Flag Count",
                "PSH Flag Count",
                "ACK Flag Count",
                "URG Flag Count",
                "CWE Flag Count",
                "ECE Flag Count",
                "Down/Up Ratio",
                "Avg Packet Size",
                "Avg Fwd Segment Size",
                "Avg Bwd Segment Size",
                "Fwd Avg Bytes/Bulk",
                "Fwd Avg Packets/Bulk",
                "Fwd Avg Bulk Rate",
                "Bwd Avg Bytes/Bulk",
                "Bwd Avg Packets/Bulk",
                "Bwd Avg Bulk Rate",
                "Subflow Fwd Packets",
                "Subflow Fwd Bytes",
                "Subflow Bwd Packets",
                "Subflow Bwd Bytes",
                "Init Fwd Win Bytes",
                "Init Bwd Win Bytes",
                "Fwd Act Data Packets",
                "Fwd Seg Size Min",
                "Active Mean",
                "Active Std",
                "Active Max",
                "Active Min",
                "Idle Mean",
                "Idle Std",
                "Idle Max",
                "Idle Min",
                "Label",
    file_order,
    source_file,
    capture_date,
    ingestion_order
FROM (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY
                "Protocol",
                    "Flow Duration",
                    "Total Fwd Packets",
                    "Total Backward Packets",
                    "Fwd Packets Length Total",
                    "Bwd Packets Length Total",
                    "Fwd Packet Length Max",
                    "Fwd Packet Length Min",
                    "Fwd Packet Length Mean",
                    "Fwd Packet Length Std",
                    "Bwd Packet Length Max",
                    "Bwd Packet Length Min",
                    "Bwd Packet Length Mean",
                    "Bwd Packet Length Std",
                    "Flow Bytes/s",
                    "Flow Packets/s",
                    "Flow IAT Mean",
                    "Flow IAT Std",
                    "Flow IAT Max",
                    "Flow IAT Min",
                    "Fwd IAT Total",
                    "Fwd IAT Mean",
                    "Fwd IAT Std",
                    "Fwd IAT Max",
                    "Fwd IAT Min",
                    "Bwd IAT Total",
                    "Bwd IAT Mean",
                    "Bwd IAT Std",
                    "Bwd IAT Max",
                    "Bwd IAT Min",
                    "Fwd PSH Flags",
                    "Bwd PSH Flags",
                    "Fwd URG Flags",
                    "Bwd URG Flags",
                    "Fwd Header Length",
                    "Bwd Header Length",
                    "Fwd Packets/s",
                    "Bwd Packets/s",
                    "Packet Length Min",
                    "Packet Length Max",
                    "Packet Length Mean",
                    "Packet Length Std",
                    "Packet Length Variance",
                    "FIN Flag Count",
                    "SYN Flag Count",
                    "RST Flag Count",
                    "PSH Flag Count",
                    "ACK Flag Count",
                    "URG Flag Count",
                    "CWE Flag Count",
                    "ECE Flag Count",
                    "Down/Up Ratio",
                    "Avg Packet Size",
                    "Avg Fwd Segment Size",
                    "Avg Bwd Segment Size",
                    "Fwd Avg Bytes/Bulk",
                    "Fwd Avg Packets/Bulk",
                    "Fwd Avg Bulk Rate",
                    "Bwd Avg Bytes/Bulk",
                    "Bwd Avg Packets/Bulk",
                    "Bwd Avg Bulk Rate",
                    "Subflow Fwd Packets",
                    "Subflow Fwd Bytes",
                    "Subflow Bwd Packets",
                    "Subflow Bwd Bytes",
                    "Init Fwd Win Bytes",
                    "Init Bwd Win Bytes",
                    "Fwd Act Data Packets",
                    "Fwd Seg Size Min",
                    "Active Mean",
                    "Active Std",
                    "Active Max",
                    "Active Min",
                    "Idle Mean",
                    "Idle Std",
                    "Idle Max",
                    "Idle Min",
                    "Label"
            ORDER BY
                file_order ASC,
                ingestion_order ASC
        ) AS duplicate_rank
    FROM raw_with_provenance
)
WHERE duplicate_rank = 1;
